### ISSUE TITLE
Admin Dashboard - Implement Mailing functionality

### ISSUE THREAD

**Issue by aryeko** [tomerach/EasyVol-SWE-Project#12]
After the [DB view issue](https://github.com/tomerach/EasyVol-SWE-Project/issues/11) is done, add mailing option to the selected volunteers\organizations

Referenced to:
- Contact by mail
- [x]  [#19 - Contact coordinator By all clients](https://github.com/tomerach/EasyVol-SWE-Project/issues/19)
- [x] [#47 - Add direct mailing from Admin dashboard](https://github.com/tomerach/EasyVol-SWE-Project/issues/47)
- Notify the coordinator when organization assigned a volunteer 
- [x] [#11 - start volunteering button](https://github.com/tomerach/EasyVol-SWE-Project/issues/11) 

**Points: 4**

**Comment by tomerach** [comment]
All referenced issues has implemented successfully.
